server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka
    # 表示是否将自己注册进eureka注册中心
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认为true。单点模式下无所谓，使用集群时必须要设置为true才能配合ribbon使用负载均衡
    fetch-registry: true