server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com  #eureka服务器的实例名称
  client:
    # false表示自己就是注册中心，职责就是维护服务实例，不需要去检索服务
    fetch-registry: false
    # 是否注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka7001.com:7001/eureka