server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    # false表示eureka不再向注册中心注册自己，也就是不向自己注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，职责就是维护实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka7002.com:7002/eureka
  server:
    # 关闭自我保护计值，保证不可用服务立即被剔除
    enable-self-preservation: false
    # 设置具体被剔除的时间
    eviction-interval-timer-in-ms: 2000